name: AASM build

on:
  push:
    tags:
      - v*.**

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: "Ark-Ascended-Server-Manager.exe"
            platform: windows/amd64
            os: windows-latest
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set direct proxy
        run: go env -w GOPROXY=direct
      - run: go install github.com/wailsapp/wails/cmd/wails@latest
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          build: true
          nsis: true
          package: true
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AASM Installer
          path: build/bin/*.exe
      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref }} build/bin/Ark-Ascended-Server-Manager.exe --clobber --name "Win64-Standalone"
          gh release upload ${{ github.ref }} build/bin/Ark-Ascended-Server-Manager-amd64-installer.exe --clobber --name "Win64-Installer"