name: AASM build

on:
  push:
    tags:
      - v*.**

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: Windows
            platform: windows/amd64
            os: windows-latest
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set direct proxy
        run: go env -w GOPROXY=direct
      - run: go install github.com/wailsapp/wails/cmd/wails@latest
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          build: true
          nsis: true
          package: false
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AASM Installer
          path: build/bin/*.exe
      - uses: actions/checkout@v3
      - name: Upload Release Assets
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run:
          gh release upload ${{ github.ref }} build/bin/*.exe