name: Wails build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: wailsTest, platform: windows/amd64, os: windows-latest},
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set direct proxy
        run: go env -w GOPROXY=direct
      - run: go install github.com/wailsapp/wails/cmd/wails@latest
      
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
