name: AASM build

on:
  push:
    tags:
      - v*.**

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: "Ark-Ascended-Server-Manager.exe"
            platform: windows/amd64
            os: windows-latest
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set direct proxy
        run: go env -w GOPROXY=direct
      - run: go install github.com/wailsapp/wails/cmd/wails@latest
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          build: true
          nsis: true
          package: true
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AASM Installer
          path: build/bin/*.exe
      - name: Upload Release Assets
        run: |
          gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" --hostname ${{ github.api_url }} /repos/${{ github.repository }}/releases/tag/${{ github.ref }}  -f '@Ark-Ascended-Server-Manager.exe'  -label 'Win64-Standalone'
          gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" --hostname ${{ github.api_url }} /repos/${{ github.repository }}/releases/tag/${{ github.ref }}  -f '@Ark-Ascended-Server-Manager-amd64-installer.exe' -label 'Win64-Installer'